# Generated by Django 3.1 on 2020-10-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0002_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1023)),
                ('table_name', models.CharField(max_length=1023)),
                ('photo_path', models.CharField(max_length=1023)),
            ],
        ),
    ]
