# Generated by Django 3.1 on 2020-10-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='photo_path',
        ),
        migrations.AddField(
            model_name='guest',
            name='photo',
            field=models.ImageField(default='img/guest_photos/default.jpg', upload_to='img/guest_photos'),
        ),
    ]
